### ISSUE TITLE
github-auto 的复制按钮样式在明暗切换场景显示异常

### ISSUE THREAD

**Issue by VoidYun** [halo-sigs/plugin-highlightjs#36]
#### What type of issue is this?
/kind bug

#### System information:
- 已激活主题: [Earth 1.12.3](https://github.com/halo-dev/theme-earth)
- 已启动插件: [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs)

#### What happened?
在明暗切换下复制按钮的样式没有变化

![Image](https://github.com/user-attachments/assets/78122563-f58b-47de-a362-ccdef2d6e03c)

#### What did you expect to happen?
来回切换下，亮色保持白底黑字，暗色保持黑底白字

#### How can we reproduce it (as minimally and precisely as possible)?
安装 [highlight.js 代码高亮 1.3.2](https://github.com/halo-sigs/plugin-highlightjs) 样式设置为 github-auto.min.css ，在亮色模式观察复制按钮样式，随后切换为暗色模式观察样式，然后刷新页面再观察样式

#### Anything else we need to know?
目前我的解决办法是注入下面样式，其中 `--bc-hljs` 和 `--color-hljs` 分别为 github-auto.min.css 的主题 background-color 和 color
```css
<style>
.hljs-copy-button {
    --hljs-theme-background: var(--bc-hljs);
    --hljs-theme-color: var(--color-hljs);
}
</style>
```

主要是为了覆盖
```javascript
// src/main/resources/static/plugins/highlightjs-copy.js:15

el.parentElement.style.setProperty("--hljs-theme-background", window.getComputedStyle(el).backgroundColor);
el.parentElement.style.setProperty("--hljs-theme-color", window.getComputedStyle(el).color);
````
